sudo: false
language: ruby
cache: 
  bundler: true

before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "gem update bundler"

before_script:
  - bundle update
  - RAILS_ENV=test bundle exec rails db:create db:migrate

rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - 2.3.1
  - ruby-head

matrix:
 allow_failures:
   - rvm: ruby-head
