version: "3"

volumes:
  app-db:

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    volumes:
      - app-db:/data
      - .:/app
    ports:
      - 8080:3000
    tty: true
    stdin_open: true
    command: "bundle exec rails server -p 3000"
    # command: ["apache2ctl", "-DFOREGROUND", "-DNO_DETACH"]
