version: "3.7"

services:
  app:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    command: ["./bin/start_dev_server"]
    volumes:
      - .:/usr/src/app
      - bundle:/bundle
      - db-data:/db-data
      - /usr/src/app/tmp
      - /usr/src/app/log
      - /usr/src/app/storage
    ports:
      - "3000:3000"
    env_file:
      - .env.development

volumes:
  bundle:
  db-data:
