version: '3'

volumes:
  app-db:

services:

  app:
    image: casi/app-fs:latest
    volumes:
      - app-db:/data
    env_file: .env
    working_dir: /var/www/app
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["apache2ctl", "-DFOREGROUND", "-DNO_DETACH"]
