FROM casi257/app-fs:1.0-dev as builder

# Prepare Ruby
RUN gem install bundler

# Set up user and group
RUN mkdir /app && chown www-data:www-data /app

# Add Gemfiles
WORKDIR /tmp
COPY Gemfile Gemfile.lock /tmp/

# clean install of all gems
RUN bundle install --clean --system --no-cache --with="development test" \
  && rm -rf /usr/local/bundle/cache
RUN chown -R www-data:www-data /usr/local/bundle

# use right user in the right app folder
USER www-data
WORKDIR /app
