version: "3.7"

services:
  app:
    build:
      context: .
      target: production
    command: "bundle exec rails s"
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - public:/usr/src/app/public
      - db-data:/db-data

volumes:
  db-data:
  public:
