version: '3'

services:
  bundler:
    image: casi/app-fs:1.0-dev
    volumes:
      - ./:/app

  app:
    image: casi/app-fs:1.0-dev
    volumes:
      - ./:/var/www
    ports:
      - 3000:8080
    command: ["apache2", "-DFOREGROUND"]
