name: Run CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2
      - name: Setup application
        id: setup-app
        uses: make setup
      - name: Run Spec
        id: run-spec
        uses: make
