name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Install bundler
        id: install-bundler
        run: gem install bundler
      - name: Install dependencies
        id: install-dependencies
        run: bundle install
      - name: Run Spec
        id: run-spec
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.sample config/database.yml
          bundle exec rake
